### ISSUE TITLE
Try to break homography with labeled example

### ISSUE THREAD

**Issue by IvanMalison** [billnerds/rackbrains#28]
The homography stuff should be much more robust now, we should pass every example we label through it, and see if there are cases it can't handle.

**Comment by deanwenstrand** [comment]
https://docs.google.com/spreadsheets/d/1CD5Xr9l8nhiDdHVCNW2Qoh1Wu9GRNozuRb3-lsasvSs/edit#gid=2086190184

**Comment by IvanMalison** [comment]
Lets put this on hold. We're still iterating on exactly how we're going to handle homography.

**Comment by IvanMalison** [comment]
Closing, too vague
