### ISSUE TITLE
Figure out why the status of some samples is "Unknown"

### ISSUE THREAD

**Issue by IvanMalison** [billnerds/rackbrains#32]
As part of fixing #31 I wrote this function to get the status of a sample from the workflow history:

https://github.com/IvanMalison/pool-visualization/blob/eca4c21e15be8a9479db37050f2d676eb1a443e5/rackbrains/labelbox.py#L97

I really didn't investigate the problem thoroughly, but the logic does mostly seem to work.

However, it seems that we are not able to deduce the status of some samples, which seems strange to me.

As part of this task we should:

a) Figure out why these samples have unknown status
b) Perhaps dig in to the labelbox docs and see if there is a better way to get label status. This may involve setting this configuration appropriately: https://github.com/IvanMalison/pool-visualization/blob/eca4c21e15be8a9479db37050f2d676eb1a443e5/rackbrains/containers.py#L17

**Comment by katandtonic** [comment]
When the image is in `Initial labeling task,` labelbox returns an empty workflow. So I switched the default state when there is no workflow history to `To Initial Label`

**Comment by IvanMalison** [comment]
Fixed in #33
